### PR TITLE
Finishing: Creating the Index

### PR DESCRIPTION
**Pull request by jbrandy1**
@semmypurewal Just checking to make sure that the index changes need to be in the main.jsx file

### CODE REVIEW

**Comment by semmypurewal** [comment]
Can you add a screenshot to this so I can see what it looks like?

**Comment by jbrandy1** [comment]
Yeah sorry about that
Screenshot 2024-04-29 135849

**Comment by semmypurewal** [comment]
Sorry, can you include a screenshot of the UI? So take a screenshot of the code running in the browser so I can see what the output looks like?

**Comment by jbrandy1** [comment]
Oh okay I see I just saw the email. Here is what my http://[127.0.0.1:8000] returns when I run docker compose up --build. 
Screenshot 2024-04-29 152200

**Review by semmypurewal — APPROVED** [review]
Looks great!

**Pull request merged**
